from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import black, HexColor

def _wrap_text(text, max_chars=90):
    words = text.split(" ")
    lines = []
    line = ""
    for w in words:
        if len(line) + len(w) + 1 <= max_chars:
            line = (line + " " + w).strip()
        else:
            if line:
                lines.append(line)
            line = w
    if line:
        lines.append(line)
    return lines


def build_pdf(row):
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    margin = 60
    green = HexColor("#1B5E20")
    good = HexColor("#2E7D32")
    bad = HexColor("#C62828")

    # ---------------- PAGE 1 ----------------
    y = height - 70
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(green)
    c.drawString(margin, y, "EcoWeb Sustainability Report")

    y -= 35
    c.setFont("Helvetica", 11)
    c.setFillColor(black)
    c.drawString(margin, y, f"Generated: {row['created_at']}")

    y -= 16
    c.drawString(margin, y, "Website:")
    for line in _wrap_text(str(row["url"])):
        y -= 16
        c.drawString(margin + 55, y, line)

    y -= 18
    c.line(margin, y, width - margin, y)

    # Summary
    y -= 35
    c.setFont("Helvetica-Bold", 15)
    c.drawString(margin, y, "Summary")

    y -= 24
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Page Size (HTML): {row['size']} MB")
    y -= 18
    c.drawString(margin, y, f"CO2 per visit (estimated): {row['co2']} g")

    y -= 26
    c.setFont("Helvetica-Bold", 13)
    score = int(row["score"])
    c.setFillColor(good if score >= 60 else bad)
    c.drawString(margin, y, f"Green Score: {score}/100  ({row['rating']})")
    c.setFillColor(black)

    # Composition
    y -= 45
    c.setFont("Helvetica-Bold", 15)
    c.drawString(margin, y, "Page Composition")

    y -= 24
    c.setFont("Helvetica", 12)
    c.drawString(
        margin, y,
        f"Images: {row['images']}    Scripts: {row['scripts']}    Videos: {row['videos']}    Links: {row['links']}"
    )

    # Optimization
    y -= 45
    c.setFont("Helvetica-Bold", 15)
    c.drawString(margin, y, "Before vs After (Optimization Simulation)")

    y -= 24
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"Optimized Page Size: {row['opt_size']} MB")
    y -= 18
    c.drawString(margin, y, f"Optimized CO2: {row['opt_co2']} g")

    y -= 26
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(good)
    c.drawString(margin, y, f"CO2 Saved: {row['co2_saved']} g   ({row['saved_percent']}% reduction)")
    c.setFillColor(black)

    # Footer
    y -= 60
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(margin, y, "This report was generated by EcoWeb – an AI-based carbon intelligence system for the Internet.")

    c.showPage()

    # ---------------- PAGE 2 ----------------
    y = height - 80
    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(green)
    c.drawString(margin, y, "AI Optimization Recommendations")

    y -= 35
    c.setFont("Helvetica", 12)
    c.setFillColor(black)
    c.drawString(margin, y, "Based on the website analysis, EcoWeb recommends the following actions:")

    tips = []

    if row["scripts"] > 20:
        tips.append("Reduce and bundle JavaScript files. The site has a high number of scripts, increasing energy usage.")
    if row["images"] > 25:
        tips.append("Convert images to modern formats (WebP/AVIF) and enable lazy-loading to reduce data transfer.")
    if row["links"] > 150:
        tips.append("Reduce unnecessary tracking and redirects on linked pages.")
    if row["videos"] > 0:
        tips.append("Avoid auto-playing videos and use lower resolution by default.")

    if not tips:
        tips.append("The website is already well optimized. Minor improvements in scripts and images can further reduce its carbon footprint.")

    y -= 40
    c.setFont("Helvetica", 12)
    for tip in tips:
        for line in _wrap_text("• " + tip, 95):
            c.drawString(margin, y, line)
            y -= 18
        y -= 8

    y -= 30
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "Projected Impact:")
    y -= 20
    c.setFont("Helvetica", 12)
    c.drawString(margin, y, f"If implemented, these optimizations could reduce CO2 emissions by approximately {row['saved_percent']}% per visit.")

    y -= 50
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(margin, y, "EcoWeb helps organizations make the Internet more sustainable through data-driven optimization.")

    c.showPage()
    c.save()

    buf.seek(0)
    return buf.getvalue()
